In [1]:
!ls ~/exp_builds/astera.exp/rundata/run1/6.fighter/

6.fighter	     fighter.debug	    locals.csv
6.fighter.debug      fighter.dwarf.sdb	    _raw_debug_locals.csv
6.fighter.debug.sdb  function_params.csv    _raw_dwarf_locals.csv
6.fighter.sdb	     functions.csv	    _raw_stripped_locals.csv
ast_dumps	     ghidra_ast.debug.json
fighter		     ghidra_ast.json

In [10]:
from pathlib import Path
import pandas as pd
pd.set_option('display.max_colwidth', 20)   # JSON columns make things look weird in notebook without this

sl = pd.read_csv(Path.home()/'exp_builds/astera.exp/rundata/run1/6.fighter/_raw_stripped_locals.csv')
sl

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
0,1089449,local_c,"16,28,52,76,101,...",int32,stack,NaN,-12,BUILTIN,int32
1,1089564,local_c,"16,28,52,76,101,...",int32,stack,NaN,-12,BUILTIN,int32
2,1089679,local_c,"17,29,53,79,79,87",int32,stack,NaN,-12,BUILTIN,int32
3,1089772,local_c,"21,96,96,104",int32,stack,NaN,-12,BUILTIN,int32
4,1089885,__x,"26,31",float,register,xmm0_da,4608,BUILTIN,float
...,...,...,...,...,...,...,...,...,...
8726,1765816,local_28,55,uchar[16],stack,NaN,-40,ARR,"ARR,uchar"
8727,1765816,local_18,"138,231,270",short,stack,NaN,-24,BUILTIN,short
8728,1765816,local_16,"147,176,256,299",short,stack,NaN,-22,BUILTIN,short
8729,1765816,local_14,"256,299",uint32,stack,NaN,-20,BUILTIN,uint32
8730,1765816,local_10,"19,114",int64,stack,NaN,-16,BUILTIN,int64

In [30]:
dl = pd.read_csv(Path.home()/'exp_builds/astera.exp/rundata/run1/6.fighter/_raw_debug_locals.csv')
dl

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
0,1089449,b_local,NaN,float*,stack,NaN,-48,PTR,"PTR,float"
1,1089449,a_local,NaN,float*,stack,NaN,-40,PTR,"PTR,float"
2,1089449,r_local,NaN,float*,stack,NaN,-32,PTR,"PTR,float"
3,1089449,i,"16,28,52,76,101,...",int32,stack,NaN,-12,BUILTIN,int32
4,1089564,b_local,NaN,float*,stack,NaN,-48,PTR,"PTR,float"
...,...,...,...,...,...,...,...,...,...
13846,1765816,in_FS_OFFSET,"19,114",int64,register,fs_offset,272,BUILTIN,int64
13847,1765816,mode_local,NaN,int32,stack,NaN,-52,BUILTIN,int32
13848,1765816,js_local,NaN,_GLFWjoystick*,stack,NaN,-48,PTR,"PTR,STRUCT"
13849,1765816,e,"55,138,147,176,2...",input_event,stack,NaN,-40,STRUCT,STRUCT
13850,1766138,guid_local,NaN,char*,stack,NaN,-16,PTR,"PTR,char"

In [3]:
!ls ~/dev/TYGR/test

fighter.debug  fighter.dwarf.sdb

In [4]:
import dwarflib

fighter_bin = Path.home()/'dev/TYGR/test/fighter.debug'

# ddi = dwarflib.DwarfDebugInfo.fromElf(fighter_bin)
# fdie = ddi.funcdies_by_addr[0x14ed3]
# lvars = ddi.get_function_locals(fdie)
# [(x.name, x.location_varlib) for x in lvars]

In [5]:
from datatype_recovery.experiments.basic_dataset import build_dwarf_data_tables

dw_tables = build_dwarf_data_tables(fighter_bin, get_location=True)

500/1807 (27.7%)...
1000/1807 (55.3%)...
1500/1807 (83.0%)...
Serializing DWARF sdb...

In [12]:
dw = dw_tables.locals_df
dw

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
0,ctx_info,a_ctx_info,stack,,-120,1134291,main,STRUCT,STRUCT
1,params,r_window_params,stack,,-88,1134291,main,STRUCT,STRUCT
2,delta,double,stack,,-136,1134291,main,BUILTIN,double
3,render_delta,double,stack,,-128,1134291,main,BUILTIN,double
4,table,s_table,stack,,-72,1133956,save_config,STRUCT,STRUCT
...,...,...,...,...,...,...,...,...,...
4888,axis,int32,stack,,-32,1761468,handleAbsEvent,BUILTIN,int32
4889,state,int32*,stack,,-24,1761468,handleAbsEvent,PTR,"PTR,int32"
4890,info,input_absinfo*,stack,,-16,1761468,handleAbsEvent,PTR,"PTR,STRUCT"
4891,normalized,float,stack,,-44,1761468,handleAbsEvent,BUILTIN,float
4892,range,int32,stack,,-28,1761468,handleAbsEvent,BUILTIN,int32

In [13]:
dw[dw.FunctionStart==0x114ed3]

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
0,ctx_info,a_ctx_info,stack,,-120,1134291,main,STRUCT,STRUCT
1,params,r_window_params,stack,,-88,1134291,main,STRUCT,STRUCT
2,delta,double,stack,,-136,1134291,main,BUILTIN,double
3,render_delta,double,stack,,-128,1134291,main,BUILTIN,double

In [16]:
sl[(sl.FunctionStart==0x114ed3)&(sl.LocOffset==-136)]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
566,1134291,local_88,"765,794,813",double,stack,NaN,-136,BUILTIN,double

In [19]:
dl[(dl.FunctionStart==0x114ed3)]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
626,1134291,lVar1,"16,1560",int64,unique,NaN,49792,BUILTIN,int64
627,1134291,fbo,"1219,1219,1219,1...",r_framebuffer,unique,NaN,268436935,STRUCT,STRUCT
628,1134291,fbo_00,"1428,1428,1428,1...",r_framebuffer,unique,NaN,268437655,STRUCT,STRUCT
629,1134291,params_00,"510,510,510,510,...",r_window_params,unique,NaN,268438375,STRUCT,STRUCT
630,1134291,auVar2,"510,510,510,510,...",uchar[32],unique,NaN,268438471,ARR,"ARR,uchar"
631,1134291,ctx_info_00,"198,198,198,198,...",a_ctx_info,unique,NaN,268438591,STRUCT,STRUCT
632,1134291,auVar3,"198,198,198,198,...",uchar[24],unique,NaN,268438639,ARR,"ARR,uchar"
633,1134291,uVar4,"828,833,862,867,...",uchar,register,al,0,BUILTIN,uchar
634,1134291,iVar5,"226,550,610,1551...",int32,register,eax,0,BUILTIN,int32
635,1134291,tVar6,"36,43",int64,register,rax,0,BUILTIN,int64
636,1134291,in_FS_OFFSET,"16,1560",int64,register,fs_offset,272,BUILTIN,int64
637,1134291,extraout_XMM0_Qa,709,double,register,xmm0_qa,4608,BUILTIN,double
638,1134291,extraout_XMM0_Qa_00,738,double,register,xmm0_qa,4608,BUILTIN,double
639,1134291,tVar7,"765,794,813,882,905",double,register,xmm0_qa,4608,BUILTIN,double
640,1134291,in_XMM1_Qa,"709,738",double,register,xmm1_qa,4640,BUILTIN,double
641,1134291,local_a8,77,asset_t*,stack,NaN,-168,PTR,"PTR,STRUCT"
642,1134291,local_a0,84,uint64,stack,NaN,-160,BUILTIN,uint64
643,1134291,local_98,105,uint64,stack,NaN,-152,BUILTIN,uint64
644,1134291,local_90,112,uint64,stack,NaN,-144,BUILTIN,uint64
645,1134291,delta,NaN,double,stack,NaN,-136,BUILTIN,double
646,1134291,render_delta,NaN,double,stack,NaN,-128,BUILTIN,double
647,1134291,ctx_info,NaN,a_ctx_info,stack,NaN,-120,STRUCT,STRUCT
648,1134291,params,"342,510",r_window_params,stack,NaN,-88,STRUCT,STRUCT

In [17]:
dl[(dl.FunctionStart==0x114ed3)&(dl.LocOffset==-136)]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
645,1134291,delta,NaN,double,stack,NaN,-136,BUILTIN,double

In [31]:
dl['LocRegName'] = dl.LocRegName.fillna('')
dl[dl.LocRegName.isna()]

Empty DataFrame
Columns: [FunctionStart, Name, Signature, Type, LocType, LocRegName, LocOffset, TypeCategory, TypeSeq]
Index: []

In [36]:
y = sl.merge(dw, how='outer', on=['FunctionStart','LocType','LocRegName','LocOffset'], suffixes=['_Strip','_DWARF'])
y[y.FunctionStart==0x114ed3].sort_values(by='Name_DWARF')

,FunctionStart,Name_Strip,Signature,Type_Strip,LocType,LocRegName,LocOffset,TypeCategory_Strip,TypeSeq_Strip,Name_DWARF,Type_DWARF,FunctionName,TypeCategory_DWARF,TypeSeq_DWARF
582,1134291,local_78,119,uint64,stack,,-120,BUILTIN,uint64,ctx_info,a_ctx_info,main,STRUCT,STRUCT
580,1134291,local_88,"765,794,813",double,stack,,-136,BUILTIN,double,delta,double,main,BUILTIN,double
586,1134291,local_58,342,uint64,stack,,-88,BUILTIN,uint64,params,r_window_params,main,STRUCT,STRUCT
581,1134291,local_80,"882,905",uint64,stack,,-128,BUILTIN,uint64,render_delta,double,main,BUILTIN,double
570,1134291,cVar1,"828,833,862,867,...",char,register,al,0,BUILTIN,char,NaN,NaN,NaN,NaN,NaN
571,1134291,tVar2,"36,43",int64,register,rax,0,BUILTIN,int64,NaN,NaN,NaN,NaN,NaN
572,1134291,uVar3,"226,550,610,1551...",uint64,register,rax,0,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
573,1134291,in_FS_OFFSET,"16,1560",int64,register,fs_offset,272,BUILTIN,int64,NaN,NaN,NaN,NaN,NaN
574,1134291,auVar4,"789,789,794",uchar[16],register,xmm0,4608,ARR,"ARR,uchar",NaN,NaN,NaN,NaN,NaN
575,1134291,auVar5,"794,794,799",uchar[16],register,xmm0,4608,ARR,"ARR,uchar",NaN,NaN,NaN,NaN,NaN
576,1134291,local_a8,"48,77",uint64,stack,,-168,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
577,1134291,local_a0,84,uint64,stack,,-160,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
578,1134291,local_98,105,uint64,stack,,-152,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
579,1134291,local_90,112,uint64,stack,,-144,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
583,1134291,local_70,161,uint64,stack,,-112,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
584,1134291,local_68,173,uint64,stack,,-104,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
585,1134291,local_60,179,uint64,stack,,-96,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
587,1134291,local_50,279,uint64,stack,,-80,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
588,1134291,local_48,287,uint64,stack,,-72,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
589,1134291,local_40,295,uint64,stack,,-64,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
590,1134291,local_38,345,uint64,stack,,-56,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
591,1134291,local_30,357,uint64,stack,,-48,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
592,1134291,local_28,369,char*,stack,,-40,PTR,"PTR,char",NaN,NaN,NaN,NaN,NaN
593,1134291,local_20,"16,1560",int64,stack,,-32,BUILTIN,int64,NaN,NaN,NaN,NaN,NaN
594,1134291,extraout_XMM0_Qb,789,uint64,NaN,,0,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN

In [32]:
x = dl.merge(dw, how='outer', on=['FunctionStart','LocType','LocRegName','LocOffset'], suffixes=['_Debug','_DWARF'])
x[x.FunctionStart==0x114ed3]

,FunctionStart,Name_Debug,Signature,Type_Debug,LocType,LocRegName,LocOffset,TypeCategory_Debug,TypeSeq_Debug,Name_DWARF,Type_DWARF,FunctionName,TypeCategory_DWARF,TypeSeq_DWARF
640,1134291,lVar1,"16,1560",int64,unique,,49792,BUILTIN,int64,NaN,NaN,NaN,NaN,NaN
641,1134291,fbo,"1219,1219,1219,1...",r_framebuffer,unique,,268436935,STRUCT,STRUCT,NaN,NaN,NaN,NaN,NaN
642,1134291,fbo_00,"1428,1428,1428,1...",r_framebuffer,unique,,268437655,STRUCT,STRUCT,NaN,NaN,NaN,NaN,NaN
643,1134291,params_00,"510,510,510,510,...",r_window_params,unique,,268438375,STRUCT,STRUCT,NaN,NaN,NaN,NaN,NaN
644,1134291,auVar2,"510,510,510,510,...",uchar[32],unique,,268438471,ARR,"ARR,uchar",NaN,NaN,NaN,NaN,NaN
645,1134291,ctx_info_00,"198,198,198,198,...",a_ctx_info,unique,,268438591,STRUCT,STRUCT,NaN,NaN,NaN,NaN,NaN
646,1134291,auVar3,"198,198,198,198,...",uchar[24],unique,,268438639,ARR,"ARR,uchar",NaN,NaN,NaN,NaN,NaN
647,1134291,uVar4,"828,833,862,867,...",uchar,register,al,0,BUILTIN,uchar,NaN,NaN,NaN,NaN,NaN
648,1134291,iVar5,"226,550,610,1551...",int32,register,eax,0,BUILTIN,int32,NaN,NaN,NaN,NaN,NaN
649,1134291,tVar6,"36,43",int64,register,rax,0,BUILTIN,int64,NaN,NaN,NaN,NaN,NaN
650,1134291,in_FS_OFFSET,"16,1560",int64,register,fs_offset,272,BUILTIN,int64,NaN,NaN,NaN,NaN,NaN
651,1134291,extraout_XMM0_Qa,709,double,register,xmm0_qa,4608,BUILTIN,double,NaN,NaN,NaN,NaN,NaN
652,1134291,extraout_XMM0_Qa_00,738,double,register,xmm0_qa,4608,BUILTIN,double,NaN,NaN,NaN,NaN,NaN
653,1134291,tVar7,"765,794,813,882,905",double,register,xmm0_qa,4608,BUILTIN,double,NaN,NaN,NaN,NaN,NaN
654,1134291,in_XMM1_Qa,"709,738",double,register,xmm1_qa,4640,BUILTIN,double,NaN,NaN,NaN,NaN,NaN
655,1134291,local_a8,77,asset_t*,stack,,-168,PTR,"PTR,STRUCT",NaN,NaN,NaN,NaN,NaN
656,1134291,local_a0,84,uint64,stack,,-160,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
657,1134291,local_98,105,uint64,stack,,-152,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
658,1134291,local_90,112,uint64,stack,,-144,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN
659,1134291,delta,NaN,double,stack,,-136,BUILTIN,double,delta,double,main,BUILTIN,double
660,1134291,render_delta,NaN,double,stack,,-128,BUILTIN,double,render_delta,double,main,BUILTIN,double
661,1134291,ctx_info,NaN,a_ctx_info,stack,,-120,STRUCT,STRUCT,ctx_info,a_ctx_info,main,STRUCT,STRUCT
662,1134291,params,"342,510",r_window_params,stack,,-88,STRUCT,STRUCT,params,r_window_params,main,STRUCT,STRUCT

In [34]:
#y = sl.merge(dw, how='outer')
sl['LocRegName'] = sl.LocRegName.fillna('')
sl[sl.LocRegName.isna()]

Empty DataFrame
Columns: [FunctionStart, Name, Signature, Type, LocType, LocRegName, LocOffset, TypeCategory, TypeSeq]
Index: []

In [1]:
!ls ~/dev/TYGR

environment.yml		    model      test_results
fighter.debug.BASE.pk1	    readme.md  test_results2
fighter.debug.pk1	    scripts    test_results3
fighter.debug_TEST.pkl	    src        tests
fighter.debug_TEST.pkl.csv  test       TYGR

In [3]:
import pickle
from pathlib import Path
from wildebeest.utils import cd

with cd(Path.home()/'dev/TYGR'):
    with open(Path.home()/'dev/TYGR/fighter.debug_TEST.pkl', 'rb') as f:
        d = pickle.load(f)

ModuleNotFoundError: No module named 'src'