In [11]:
!ls ~/exp_builds/astera.exp/rundata/run1/6.fighter/

6.fighter	     fighter.debug	    locals.csv
6.fighter.debug      fighter.dwarf.sdb	    _raw_debug_locals.csv
6.fighter.debug.sdb  function_params.csv    _raw_dwarf_locals.csv
6.fighter.sdb	     functions.csv	    _raw_stripped_locals.csv
ast_dumps	     ghidra_ast.debug.json
fighter		     ghidra_ast.json

In [12]:
from pathlib import Path
import pandas as pd
pd.set_option('display.max_colwidth', 20)   # JSON columns make things look weird in notebook without this

df = pd.read_csv(Path.home()/'exp_builds/astera.exp/rundata/run1/6.fighter/_raw_dwarf_locals.csv')
df

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
0,ctx_info,a_ctx_info,UndefinedLoc,NaN,NaN,1134291,main,STRUCT,STRUCT
1,params,r_window_params,UndefinedLoc,NaN,NaN,1134291,main,STRUCT,STRUCT
2,delta,double,UndefinedLoc,NaN,NaN,1134291,main,BUILTIN,double
3,render_delta,double,UndefinedLoc,NaN,NaN,1134291,main,BUILTIN,double
4,table,s_table,UndefinedLoc,NaN,NaN,1133956,save_config,STRUCT,STRUCT
...,...,...,...,...,...,...,...,...,...
4888,axis,int32,UndefinedLoc,NaN,NaN,1761468,handleAbsEvent,BUILTIN,int32
4889,state,int32*,UndefinedLoc,NaN,NaN,1761468,handleAbsEvent,PTR,"PTR,int32"
4890,info,input_absinfo*,UndefinedLoc,NaN,NaN,1761468,handleAbsEvent,PTR,"PTR,STRUCT"
4891,normalized,float,UndefinedLoc,NaN,NaN,1761468,handleAbsEvent,BUILTIN,float
4892,range,int32,UndefinedLoc,NaN,NaN,1761468,handleAbsEvent,BUILTIN,int32

In [18]:
!ls ~/dev/TYGR/test

fighter.debug

In [19]:
import dwarflib

fighter_bin = Path.home()/'dev/TYGR/test/fighter.debug'

# ddi = dwarflib.DwarfDebugInfo.fromElf(fighter_bin)
# fdie = ddi.funcdies_by_addr[0x14ed3]
# lvars = ddi.get_function_locals(fdie)
# [(x.name, x.location_varlib) for x in lvars]

In [35]:
from datatype_recovery.experiments.basic_dataset import build_dwarf_data_tables

dw_tables = build_dwarf_data_tables(fighter_bin, get_location=True)

500/1807 (27.7%)...
1000/1807 (55.3%)...
1500/1807 (83.0%)...
Serializing DWARF sdb...

In [37]:
dw_tables.locals_df

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
0,ctx_info,a_ctx_info,UndefinedLoc,,<NA>,1134291,main,STRUCT,STRUCT
1,params,r_window_params,UndefinedLoc,,<NA>,1134291,main,STRUCT,STRUCT
2,delta,double,UndefinedLoc,,<NA>,1134291,main,BUILTIN,double
3,render_delta,double,UndefinedLoc,,<NA>,1134291,main,BUILTIN,double
4,table,s_table,UndefinedLoc,,<NA>,1133956,save_config,STRUCT,STRUCT
...,...,...,...,...,...,...,...,...,...
4888,axis,int32,UndefinedLoc,,<NA>,1761468,handleAbsEvent,BUILTIN,int32
4889,state,int32*,UndefinedLoc,,<NA>,1761468,handleAbsEvent,PTR,"PTR,int32"
4890,info,input_absinfo*,UndefinedLoc,,<NA>,1761468,handleAbsEvent,PTR,"PTR,STRUCT"
4891,normalized,float,UndefinedLoc,,<NA>,1761468,handleAbsEvent,BUILTIN,float
4892,range,int32,UndefinedLoc,,<NA>,1761468,handleAbsEvent,BUILTIN,int32

In [13]:
df[df.FunctionStart==0x114ed3]

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
0,ctx_info,a_ctx_info,UndefinedLoc,NaN,NaN,1134291,main,STRUCT,STRUCT
1,params,r_window_params,UndefinedLoc,NaN,NaN,1134291,main,STRUCT,STRUCT
2,delta,double,UndefinedLoc,NaN,NaN,1134291,main,BUILTIN,double
3,render_delta,double,UndefinedLoc,NaN,NaN,1134291,main,BUILTIN,double